# Generated by Django 4.0 on 2021-12-18 21:56

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserGeneralInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя пользователя')),
                ('user_vk', models.URLField(verbose_name='Ссылка на vk')),
                ('user_tg', models.CharField(blank=True, max_length=100, verbose_name='Ссылка на tg')),
                ('chat_id', models.CharField(max_length=200, verbose_name='id чата с пользователем')),
                ('avatar', models.CharField(max_length=500, verbose_name='file_id аватарки')),
                ('user_about', models.CharField(max_length=1000, verbose_name='О себе')),
                ('user_age', models.IntegerField(verbose_name='Возраст пользователя')),
                ('user_gender', models.BooleanField(verbose_name='Пол пользователя - Мужской')),
                ('user_class', models.IntegerField(verbose_name='Курс пользователя')),
                ('neighbor_about', models.CharField(max_length=1000, verbose_name='О соседе')),
                ('liked_user', models.ManyToManyField(blank=True, to='bot.UserGeneralInformation')),
            ],
            options={
                'verbose_name': 'Основная информация о пользователе',
                'verbose_name_plural': 'Основная информация о пользователях',
            },
        ),
        migrations.CreateModel(
            name='UserStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_active', models.BooleanField(verbose_name='Активна ли анкета')),
                ('user_intention', models.IntegerField(verbose_name='Соседа в квартиру(1) / Квартиру с соседом(2) / Соседа для поиска Квартиры(3)')),
                ('status_for_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.usergeneralinformation')),
            ],
            options={
                'verbose_name': 'Статус пользователя',
                'verbose_name_plural': 'Статус пользователя',
            },
        ),
        migrations.CreateModel(
            name='UserCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_price', models.IntegerField(blank=True, null=True, verbose_name='Какая цена квартиры устроит')),
                ('neighbor_gender', models.IntegerField(verbose_name='Важен ли пол соседа?')),
                ('neighbor_class', models.IntegerField(verbose_name='Важен ли курс соседа?')),
                ('for_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.usergeneralinformation')),
            ],
            options={
                'verbose_name': 'Критерии пользователя',
                'verbose_name_plural': 'Критерии пользователя',
            },
        ),
        migrations.CreateModel(
            name='ApartmentOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metro', models.CharField(blank=True, max_length=100, verbose_name='Станция метро квартиры')),
                ('address', models.CharField(blank=True, max_length=100, verbose_name='Точный адрес квартиры')),
                ('time_to_hse', models.CharField(blank=True, max_length=300, verbose_name='Время до корпусов вышки от квартиры')),
                ('price', models.IntegerField(blank=True, verbose_name='Цена квартиры')),
                ('about_apartment', models.TextField(blank=True, verbose_name='О квартире')),
                ('apartment_images', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1000), size=None), size=None)),
                ('apartment_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.usergeneralinformation')),
            ],
            options={
                'verbose_name': 'Информация о квартире',
                'verbose_name_plural': 'Информация о квартире',
            },
        ),
    ]
