# Generated by Django 4.0 on 2021-12-20 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergeneralinformation',
            name='user_tg',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ссылка на tg'),
        ),
    ]
