# Generated by Django 4.0 on 2021-12-29 11:56

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_usercriteria_required_metro'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergeneralinformation',
            name='watched_profiles',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=None), default=[], size=None),
        ),
        migrations.AlterField(
            model_name='usergeneralinformation',
            name='user_vk',
            field=models.URLField(verbose_name='Ссылки на соцсети'),
        ),
        migrations.AlterField(
            model_name='userstatus',
            name='user_intention',
            field=models.IntegerField(verbose_name='Соседа в квартиру(1) / Квартиру(2)'),
        ),
    ]
