# Generated by Django 4.0 on 2022-02-03 22:42

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0008_alter_usergeneralinformation_matches_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartmentowner',
            name='apartment_images',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1000), size=None),
        ),
    ]
