# Generated by Django 4.0 on 2022-02-04 00:47

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0009_alter_apartmentowner_apartment_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergeneralinformation',
            name='watched_matches',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, null=True, size=None),
        ),
    ]
